[mcp_servers.postman]
url = "https://mcp.postman.com/mcp"

[mcp_servers.postman.tools.updateCollectionRequest]
approval_mode = "approve"

[mcp_servers.postman.tools.updateCollectionFolder]
approval_mode = "approve"

[mcp_servers.postman.tools.deleteCollectionRequest]
approval_mode = "approve"

[mcp_servers.postman.tools.createCollectionRequest]
approval_mode = "approve"

[mcp_servers.postman.tools.putEnvironment]
approval_mode = "approve"

[mcp_servers.sequential-thinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

[mcp_servers.sequential-thinking.env]
DISABLE_THOUGHT_LOGGING = "true"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]
startup_timeout_sec = 20

[mcp_servers.context7.env]
CONTEXT7_API_KEY = "<SET_IN_LOCAL_CODEX_CONFIG>"

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/deng/.codex"
CODEX_HOME = "/Users/deng/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "27dca86fd6b571c49414a4b78e46b57bcf683a46cd1319799c11fbb6cfae3110"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.609.41114"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

